# GitHub Actions workflow for Azure deployment (Vite + Node backend)
# Project structure:
# dorm-finder/
# ├── client/
# └── server/

name: Build and deploy Node.js app to Azure Web App - dormfinder-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Step 1 — Build Vite frontend
      - name: Install and build client
        working-directory: ./dorm-finder/client
        run: |
          npm install
          npm run build

      # Step 2 — Install backend dependencies
      - name: Install server dependencies
        working-directory: ./dorm-finder/server
        run: npm install

      # Step 3 — Copy client build output to server (for Express static serve)
      - name: Copy client dist to server
        run: |
          mkdir -p dorm-finder/server/client/dist
          cp -r dorm-finder/client/dist/* dorm-finder/server/client/dist/

      # Step 4 — Create ZIP for deployment
      - name: Create ZIP artifact
        run: |
          cd dorm-finder
          zip -r ../release.zip server

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_389FF293126D48508C0A8B2DED097C8E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_88BC8E4009AA488C854CCD30EF581416 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_65E65222321D4FAC8F332CB42C6EDEC3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dormfinder-webapp'
          slot-name: 'Production'
          package: ./server
